# Mapping from enum name to short display label
# Based on vial-gui's keycodes.py label field
SPECIAL_SYMBOL = {
    # Basic keys - letters (just the letter)
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "H": "H",
    "I": "I",
    "J": "J",
    "K": "K",
    "L": "L",
    "M": "M",
    "N": "N",
    "O": "O",
    "P": "P",
    "Q": "Q",
    "R": "R",
    "S": "S",
    "T": "T",
    "U": "U",
    "V": "V",
    "W": "W",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    # Numbers with shifted symbols
    "Kc1": "!\n1",
    "Kc2": "@\n2",
    "Kc3": "#\n3",
    "Kc4": "$\n4",
    "Kc5": "%\n5",
    "Kc6": "^\n6",
    "Kc7": "&\n7",
    "Kc8": "*\n8",
    "Kc9": "(\n9",
    "Kc0": ")\n0",
    # Special keys
    "Enter": "Enter",
    "Escape": "Esc",
    "Backspace": "Bksp",
    "Tab": "Tab",
    "Space": "Space",
    # Punctuation with shifted symbols
    "Minus": "_\n-",
    "Equal": "+\n=",
    "LeftBracket": "{\n[",
    "RightBracket": "}\n]",
    "Backslash": "|\n\\",
    "Semicolon": ":\n;",
    "Quote": "\"\n'",
    "Grave": "~\n`",
    "Comma": "<\n,",
    "Dot": ">\n.",
    "Slash": "?\n/",
    # Lock keys
    "CapsLock": "Caps\nLock",
    "ScrollLock": "Scroll\nLock",
    "NumLock": "Num\nLock",
    # Function keys
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
    "F13": "F13",
    "F14": "F14",
    "F15": "F15",
    "F16": "F16",
    "F17": "F17",
    "F18": "F18",
    "F19": "F19",
    "F20": "F20",
    "F21": "F21",
    "F22": "F22",
    "F23": "F23",
    "F24": "F24",
    # Navigation
    "Insert": "Insert",
    "Home": "Home",
    "PageUp": "Page\nUp",
    "Delete": "Del",
    "End": "End",
    "PageDown": "Page\nDown",
    "Right": "Right",
    "Left": "Left",
    "Down": "Down",
    "Up": "Up",
    # Numpad
    "KpSlash": "/",
    "KpAsterisk": "*",
    "KpMinus": "-",
    "KpPlus": "+",
    "KpEnter": "Num\nEnter",
    "Kp1": "1",
    "Kp2": "2",
    "Kp3": "3",
    "Kp4": "4",
    "Kp5": "5",
    "Kp6": "6",
    "Kp7": "7",
    "Kp8": "8",
    "Kp9": "9",
    "Kp0": "0",
    "KpDot": ".",
    "KpEqual": "=",
    "KpComma": ",",
    # Modifiers
    "LCtrl": "LCtrl",
    "LShift": "LShift",
    "LAlt": "LAlt",
    "LGui": "LGui",
    "RCtrl": "RCtrl",
    "RShift": "RShift",
    "RAlt": "RAlt",
    "RGui": "RGui",
    # System keys
    "Application": "Menu",
    "PrintScreen": "Print\nScreen",
    "Pause": "Pause",
    # Shifted keycodes
    "Tild": "~",
    "Exlm": "!",
    "At": "@",
    "Hash": "#",
    "Dlr": "$",
    "Perc": "%",
    "Circ": "^",
    "Ampr": "&",
    "Astr": "*",
    "Lprn": "(",
    "Rprn": ")",
    "Unds": "_",
    "Plus": "+",
    "Lcbr": "{",
    "Rcbr": "}",
    "Lt": "<",
    "Gt": ">",
    "Coln": ":",
    "Pipe": "|",
    "Ques": "?",
    "Dquo": '"',
    # International
    "NonusHash": "~\n#",
    "NonusBackslash": "|\n\\",
    "Ro": "_\n\\",
    "Kana": "カタカナ\nひらがな",
    "Jyen": "|\n¥",
    "Henk": "変換",
    "Mhen": "無変換",
    "Lang1": "한영\nかな",
    "Lang2": "漢字\n英数",
    # Special QMK keycodes
    "GraveEscape": "~\nEsc",
    "SpaceCadetLShiftParenthesisOpen": "LS\n(",
    "SpaceCadetRShiftParenthesisClose": "RS\n)",
    "SpaceCadetLCtrlParenthesisOpen": "LC\n(",
    "SpaceCadetRCtrlParenthesisClose": "RC\n)",
    "SpaceCadetLAltParenthesisOpen": "LA\n(",
    "SpaceCadetRAltParenthesisClose": "RA\n)",
    # Media keys
    "KbPower": "Power",
    "SystemSleep": "Sleep",
    "SystemWake": "Wake",
    "Execute": "Exec",
    "Help": "Help",
    "Select": "Select",
    "Stop": "Stop",
    "Again": "Again",
    "Undo": "Undo",
    "Cut": "Cut",
    "Copy": "Copy",
    "Paste": "Paste",
    "Find": "Find",
    "Calc": "Calc",
    "Mail": "Mail",
    "MediaSelect": "Media\nPlayer",
    "MyComputer": "My\nPC",
    "WwwSearch": "Browser\nSearch",
    "WwwHome": "Browser\nHome",
    "WwwBack": "Browser\nBack",
    "WwwForward": "Browser\nForward",
    "WwwStop": "Browser\nStop",
    "WwwRefresh": "Browser\nRefresh",
    "WwwFavorites": "Browser\nFav.",
    "BrightnessUp": "Bright.\nUp",
    "BrightnessDown": "Bright.\nDown",
    "MediaPreviousTrack": "Media\nPrev",
    "MediaNextTrack": "Media\nNext",
    "AudioMute": "Mute",
    "AudioVolDown": "Vol -",
    "AudioVolUp": "Vol +",
    "MediaStop": "Media\nStop",
    "MediaPlayPause": "Media\nPlay",
    "MediaRewind": "Prev\nTrack\n(macOS)",
    "MediaFastForward": "Next\nTrack\n(macOS)",
    "MediaEject": "Eject",
    # Mouse keys
    "MsUp": "Mouse\nUp",
    "MsDown": "Mouse\nDown",
    "MsLeft": "Mouse\nLeft",
    "MsRight": "Mouse\nRight",
    "MsBtn1": "Mouse\n1",
    "MsBtn2": "Mouse\n2",
    "MsBtn3": "Mouse\n3",
    "MsBtn4": "Mouse\n4",
    "MsBtn5": "Mouse\n5",
    "MsWhUp": "Mouse\nWheel\nUp",
    "MsWhDown": "Mouse\nWheel\nDown",
    "MsWhLeft": "Mouse\nWheel\nLeft",
    "MsWhRight": "Mouse\nWheel\nRight",
    "MsAccel0": "Mouse\nAccel\n0",
    "MsAccel1": "Mouse\nAccel\n1",
    "MsAccel2": "Mouse\nAccel\n2",
    # Locking keys
    "LockingCapsLock": "Locking\nCaps",
    "LockingNumLock": "Locking\nNum",
    "LockingScrollLock": "Locking\nScroll",
    # Backlight (0x0600 range)
    "BacklightOn": "BL On",
    "BacklightOff": "BL Off",
    "BacklightToggle": "BL\nToggle",
    "BacklightDown": "BL -",
    "BacklightUp": "BL +",
    "BacklightStep": "BL\nCycle",
    "BacklightToggleBreathing": "BL\nBreath",
    # RGB (0x0620 range)
    "RgbTog": "RGB\nToggle",
    "RgbModeForward": "RGB\nMode +",
    "RgbModeReverse": "RGB\nMode -",
    "RgbHui": "Hue +",
    "RgbHud": "Hue -",
    "RgbSai": "Sat +",
    "RgbSad": "Sat -",
    "RgbVai": "Bright +",
    "RgbVad": "Bright -",
    "RgbSpi": "Effect +",
    "RgbSpd": "Effect -",
    "RgbModePlain": "RGB\nMode P",
    "RgbModeBreathe": "RGB\nMode B",
    "RgbModeRainbow": "RGB\nMode R",
    "RgbModeSwirl": "RGB\nMode SW",
    "RgbModeSnake": "RGB\nMode SN",
    "RgbModeKnight": "RGB\nMode K",
    "RgbModeXmas": "RGB\nMode X",
    "RgbModeGradient": "RGB\nMode G",
    "RgbModeRgbtest": "RGB\nMode T",
    "RgbModeTwinkle": "RGB\nMode TW",
    # RGB Matrix (0x7840 range)
    "RmOn": "RM\nOn",
    "RmOff": "RM\nOff",
    "RmTogg": "RM\nToggle",
    "RmNext": "RM\nNext",
    "RmPrev": "RM\nPrev",
    "RmHueu": "RM\nHue +",
    "RmHued": "RM\nHue -",
    "RmSatu": "RM\nSat +",
    "RmSatd": "RM\nSat -",
    "RmValu": "RM\nBright +",
    "RmVald": "RM\nBright -",
    "RmSpdu": "RM\nSpeed +",
    "RmSpdd": "RM\nSpeed -",
    # Boot/System
    "Bootloader": "Boot-\nloader",
    "Reboot": "Reboot",
    "DebugToggle": "Debug\nToggle",
    "ClearEeprom": "Clear\nEEPROM",
    "Make": "Make",
    "QkBoot": "Boot-\nloader",
    "QkReboot": "Reboot",
    "QkClearEeprom": "Clear\nEEPROM",
    # Caps Word
    "QkCapsWordToggle": "Caps\nWord",
    # Repeat
    "QkRepeatKey": "Repeat",
    "QkAltRepeatKey": "Alt\nRepeat",
    "QkLayerLock": "Layer\nLock",
    # Dynamic Macros
    "DynRecStart1": "DM1\nRec",
    "DynRecStart2": "DM2\nRec",
    "DynRecStop": "DM Rec\nStop",
    "DynMacroPlay1": "DM1\nPlay",
    "DynMacroPlay2": "DM2\nPlay",
    # Velocikey
    "VelocikeyToggle": "Velocikey\nToggle",
    # MIDI
    "MiC": "ᴹᴵᴰᴵ\nC",
    "MiCs": "ᴹᴵᴰᴵ\nC#/Dᵇ",
    "MiD": "ᴹᴵᴰᴵ\nD",
    "MiDs": "ᴹᴵᴰᴵ\nD#/Eᵇ",
    "MiE": "ᴹᴵᴰᴵ\nE",
    "MiF": "ᴹᴵᴰᴵ\nF",
    "MiFs": "ᴹᴵᴰᴵ\nF#/Gᵇ",
    "MiG": "ᴹᴵᴰᴵ\nG",
    "MiGs": "ᴹᴵᴰᴵ\nG#/Aᵇ",
    "MiA": "ᴹᴵᴰᴵ\nA",
    "MiAs": "ᴹᴵᴰᴵ\nA#/Bᵇ",
    "MiB": "ᴹᴵᴰᴵ\nB",
    # Magic/Quantum (0x0100 range)
    "MagicSwapControlCapsLock": "Swap\nCtrl\nCaps",
    "MagicUnswapControlCapsLock": "Unswap\nCtrl\nCaps",
    "MagicToggleControlCapsLock": "Toggle\nCtrl\nCaps",
    "MagicCapsLockAsControlOff": "Caps\nnot to\nCtrl",
    "MagicCapsLockAsControlOn": "Caps\nto\nCtrl",
    "MagicSwapLaltLGui": "Swap\nLAlt\nLGui",
    "MagicUnswapLaltLGui": "Unswap\nLAlt\nLGui",
    "MagicSwapRaltRGui": "Swap\nRAlt\nRGui",
    "MagicUnswapRaltRGui": "Unswap\nRAlt\nRGui",
    "MagicGuiOn": "GUI\nOn",
    "MagicGuiOff": "GUI\nOff",
    "MagicToggleGui": "GUI\nToggle",
    "MagicSwapGraveEsc": "Swap\n`\nEsc",
    "MagicUnswapGraveEsc": "Unswap\n`\nEsc",
    "MagicSwapBackslashBackspace": "Swap\n\\\nBS",
    "MagicUnswapBackslashBackspace": "Unswap\n\\\nBS",
    "MagicToggleBackslashBackspace": "Toggle\n\\\nBS",
    "MagicNkroOn": "NKRO\nOn",
    "MagicNkroOff": "NKRO\nOff",
    "MagicToggleNkro": "NKRO\nToggle",
    "MagicSwapAltGui": "Swap\nAlt\nGui",
    "MagicUnswapAltGui": "Unswap\nAlt\nGui",
    "MagicToggleAltGui": "Toggle\nAlt\nGui",
    "MagicSwapLctlLGui": "Swap\nLCtl\nLGui",
    "MagicUnswapLctlLGui": "Unswap\nLCtl\nLGui",
    "MagicSwapRctlRGui": "Swap\nRCtl\nRGui",
    "MagicUnswapRctlRGui": "Unswap\nRCtl\nRGui",
    "MagicSwapCtlGui": "Swap\nCtl\nGui",
    "MagicUnswapCtlGui": "Unswap\nCtl\nGui",
    "MagicToggleCtlGui": "Toggle\nCtl\nGui",
    "MagicEeHandsLeft": "EEH\nLeft",
    "MagicEeHandsRight": "EEH\nRight",
    "MagicSwapEscapeCapsLock": "Swap\nEsc\nCaps",
    "MagicUnswapEscapeCapsLock": "Unswap\nEsc\nCaps",
    "MagicToggleEscapeCapsLock": "Toggle\nEsc\nCaps",
    # Leader
    "Leader": "Leader",
    # Combo
    "ComboOn": "Combo\nOn",
    "ComboOff": "Combo\nOff",
    "ComboToggle": "Combo\nToggle",
    # Auto Shift
    "AutoShiftDown": "Auto-\nshift\nDown",
    "AutoShiftUp": "Auto-\nshift\nUp",
    "AutoShiftReport": "Auto-\nshift\nReport",
    "AutoShiftOn": "Auto-\nshift\nOn",
    "AutoShiftOff": "Auto-\nshift\nOff",
    "AutoShiftToggle": "Auto-\nshift\nToggle",
    # One Shot Mods
    "Osm(MOD_LSFT)": "OSM\nLSft",
    "Osm(MOD_LCTL)": "OSM\nLCtl",
    "Osm(MOD_LALT)": "OSM\nLAlt",
    "Osm(MOD_LGUI)": "OSM\nLGUI",
    "Osm(MOD_RSFT)": "OSM\nRSft",
    "Osm(MOD_RCTL)": "OSM\nRCtl",
    "Osm(MOD_RALT)": "OSM\nRAlt",
    "Osm(MOD_RGUI)": "OSM\nRGUI",
    # Haptic
    "HptOn": "Haptic\nOn",
    "HptOff": "Haptic\nOff",
    "HptTog": "Haptic\nToggle",
    "HptRst": "Haptic\nReset",
    "HptFbk": "Haptic\nFeed\nback",
    "HptBuz": "Haptic\nBuzz",
    "HptModi": "Haptic\nNext",
    "HptModd": "Haptic\nPrev",
    "HptCont": "Haptic\nCont.",
    "HptConi": "Haptic\n+",
    "HptCond": "Haptic\n-",
    "HptDwli": "Haptic\nDwell+",
    "HptDwld": "Haptic\nDwell-",
    # Audio
    "AuOn": "Audio\nON",
    "AuOff": "Audio\nOFF",
    "AuTog": "Audio\nToggle",
    "ClickyToggle": "Clicky\nToggle",
    "ClickyUp": "Clicky\nUp",
    "ClickyDown": "Clicky\nDown",
    "ClickyReset": "Clicky\nReset",
    "MuOn": "Music\nOn",
    "MuOff": "Music\nOff",
    "MuTog": "Music\nToggle",
    "MuMod": "Music\nCycle",
    # Macro (序号键)
    "Macro0": "Macro 0",
    "Macro1": "Macro 1",
    "Macro2": "Macro 2",
    "Macro3": "Macro 3",
    "Macro4": "Macro 4",
    "Macro5": "Macro 5",
    "Macro6": "Macro 6",
    "Macro7": "Macro 7",
    "Macro8": "Macro 8",
    "Macro9": "Macro 9",
    "Macro10": "Macro 10",
    "Macro11": "Macro 11",
    "Macro12": "Macro 12",
    "Macro13": "Macro 13",
    "Macro14": "Macro 14",
    "Macro15": "Macro 15",
    "Macro16": "Macro 16",
    "Macro17": "Macro 17",
    "Macro18": "Macro 18",
    "Macro19": "Macro 19",
    "Macro20": "Macro 20",
    "Macro21": "Macro 21",
    "Macro22": "Macro 22",
    "Macro23": "Macro 23",
    "Macro24": "Macro 24",
    "Macro25": "Macro 25",
    "Macro26": "Macro 26",
    "Macro27": "Macro 27",
    "Macro28": "Macro 28",
    "Macro29": "Macro 29",
    "Macro30": "Macro 30",
    "Macro31": "Macro 31",
    # Dynamic Macros
    "DynamicMacroRecordStart1": "DM1\nRec",
    "DynamicMacroRecordStart2": "DM2\nRec",
    "DynamicMacroRecordStop": "DM Rec\nStop",
    "DynamicMacroPlay1": "DM1\nPlay",
    "DynamicMacroPlay2": "DM2\nPlay",
    # Layer keys (MO, DF, TG, TT, TO, OSL, PDF) - vial-gui 格式
    "MO(0)": "MO(0)",
    "MO(1)": "MO(1)",
    "MO(2)": "MO(2)",
    "MO(3)": "MO(3)",
    "MO(4)": "MO(4)",
    "MO(5)": "MO(5)",
    "MO(6)": "MO(6)",
    "MO(7)": "MO(7)",
    "DF(0)": "DF(0)",
    "DF(1)": "DF(1)",
    "DF(2)": "DF(2)",
    "DF(3)": "DF(3)",
    "DF(4)": "DF(4)",
    "DF(5)": "DF(5)",
    "DF(6)": "DF(6)",
    "DF(7)": "DF(7)",
    "TG(0)": "TG(0)",
    "TG(1)": "TG(1)",
    "TG(2)": "TG(2)",
    "TG(3)": "TG(3)",
    "TG(4)": "TG(4)",
    "TG(5)": "TG(5)",
    "TG(6)": "TG(6)",
    "TG(7)": "TG(7)",
    "TT(0)": "TT(0)",
    "TT(1)": "TT(1)",
    "TT(2)": "TT(2)",
    "TT(3)": "TT(3)",
    "TT(4)": "TT(4)",
    "TT(5)": "TT(5)",
    "TT(6)": "TT(6)",
    "TT(7)": "TT(7)",
    "TO(0)": "TO(0)",
    "TO(1)": "TO(1)",
    "TO(2)": "TO(2)",
    "TO(3)": "TO(3)",
    "TO(4)": "TO(4)",
    "TO(5)": "TO(5)",
    "TO(6)": "TO(6)",
    "TO(7)": "TO(7)",
    "OSL(0)": "OSL(0)",
    "OSL(1)": "OSL(1)",
    "OSL(2)": "OSL(2)",
    "OSL(3)": "OSL(3)",
    "OSL(4)": "OSL(4)",
    "OSL(5)": "OSL(5)",
    "OSL(6)": "OSL(6)",
    "OSL(7)": "OSL(7)",
    "PDF(0)": "PDF(0)",
    "PDF(1)": "PDF(1)",
    "PDF(2)": "PDF(2)",
    "PDF(3)": "PDF(3)",
    "PDF(4)": "PDF(4)",
    "PDF(5)": "PDF(5)",
    "PDF(6)": "PDF(6)",
    "PDF(7)": "PDF(7)",
    "LT0(kc)": "LT0",
    "LT1(kc)": "LT1",
    "LT2(kc)": "LT2",
    "LT3(kc)": "LT3",
    "LT4(kc)": "LT4",
    "LT5(kc)": "LT5",
    "LT6(kc)": "LT6",
    "LT7(kc)": "LT7",
    # MT (Modifier Tap) keys - vial-gui 格式
    "MT(LCtrl, kc)": "MT(LCtrl)",
    "MT(RCtrl, kc)": "MT(RCtrl)",
    "MT(LShift, kc)": "MT(LSft)",
    "MT(RShift, kc)": "MT(RSft)",
    "MT(LAlt, kc)": "MT(LAlt)",
    "MT(RAlt, kc)": "MT(RAlt)",
    "MT(LGui, kc)": "MT(LGui)",
    "MT(RGui, kc)": "MT(RGui)",
    # MACRO keys - vial-gui 格式：M0, M1, M2...
    "M0": "M0",
    "M1": "M1",
    "M2": "M2",
    "M3": "M3",
    "M4": "M4",
    "M5": "M5",
    "M6": "M6",
    "M7": "M7",
    # TD (Tap Dance) keys - vial-gui 格式
    "TD(0)": "TD(0)",
    "TD(1)": "TD(1)",
    "TD(2)": "TD(2)",
    "TD(3)": "TD(3)",
    "TD(4)": "TD(4)",
    "TD(5)": "TD(5)",
    "TD(6)": "TD(6)",
    "TD(7)": "TD(7)",
}


def special_symbol(symbol: tuple[str | None, str | None]) -> tuple[str | None, str | None]:
    if symbol[1] in SPECIAL_SYMBOL:
        return symbol[0], SPECIAL_SYMBOL[symbol[1]]
    return symbol
